;(function (angular) {
	'use strict';
	angular.module('controllers.disasterOperation',[]).controller('disasterOperationCtr',disasterOperationCtr);
	function disasterOperationCtr($scope,disasterOperationSer){
    	$scope.query = disasterOperationSer.query;
    	$scope.hostComputerMessages = disasterOperationSer.hostComputerMessages;
    	$scope.turnToPage = disasterOperationSer.turnToPage;
    	$scope.initQueryParam = disasterOperationSer.initQueryParam();
        $scope.applianceMessages = disasterOperationSer.applianceMessages;
        $scope.queryApplianceMessage = disasterOperationSer.queryApplianceMessage;
        $scope.clickAppliance = disasterOperationSer.clickAppliance;
        $scope.clickSpareAppliance = disasterOperationSer.clickSpareAppliance;
        $scope.clickHostComputerMessage = disasterOperationSer.clickHostComputerMessage;
        $scope.clickSpareHostComputerMessage = disasterOperationSer.clickSpareHostComputerMessage;
        $scope.clickInterState = disasterOperationSer.clickInterState;
        $scope.clickSpareInterState = disasterOperationSer.clickSpareInterState;
        $scope.interStateMessages=disasterOperationSer.interStateMessages;
        $scope.falg=disasterOperationSer.falg;
        $scope.hideDiv=disasterOperationSer.hideDiv();
		$scope.param = disasterOperationSer.param;
		$scope.myResult = disasterOperationSer.myResult;
		/*$scope.getinformation = disasterOperationSer.getinformation;*/
		$scope.response = disasterOperationSer.response;
		$scope.submit = disasterOperationSer.submit;
        $scope.myFlag = disasterOperationSer.myFlag;
		$scope.myFlag2 = disasterOperationSer.myFlag2;
		$scope.con = disasterOperationSer.con;
		$scope.datas = disasterOperationSer.datas;
		$scope.switchCause = disasterOperationSer.switchCause();
		$scope.param = disasterOperationSer.param;
		$scope.mqMessages = disasterOperationSer.mqMessages;
    	$scope.catalog = disasterOperationSer.catalog;
		$scope.catalog=disasterOperationSer.catalog;
		$scope.flowMessage=disasterOperationSer.flowMessage;
        $scope.moduleFlagToShow=disasterOperationSer.moduleFlagToShow;
        $scope.batToShow=disasterOperationSer.batToShow;
        $scope.clickSpareCore=disasterOperationSer.clickSpareCore;
        $scope.determine=disasterOperationSer.determine;
        $scope.hideModal=disasterOperationSer.hideModal();
        $scope.clickMajorCore=disasterOperationSer.clickMajorCore;
        $scope.clickDataCompare=disasterOperationSer.clickDataCompare;
        $scope.clickMq=disasterOperationSer.clickMq;
        $scope.inPlan=disasterOperationSer.inPlan;
        $scope.nowFlow=disasterOperationSer.nowFlow;
        $scope.clickChangeHistory=disasterOperationSer.clickChangeHistory;
        $scope.returnIndex=disasterOperationSer.returnIndex;
        $scope.outPlan=disasterOperationSer.outPlan;
        $scope.toDataFlowChange=disasterOperationSer.toDataFlowChange;
        $scope.toDataCompare=disasterOperationSer.toDataCompare;
        $scope.toInPlanSpareCoreState=disasterOperationSer.toInPlanSpareCoreState;
        $scope.spareHostTurnToPage=disasterOperationSer.spareHostTurnToPage;
        $scope.spareApplianceTurnToPage=disasterOperationSer.spareApplianceTurnToPage;
        $scope.spareInterTurnToPage=disasterOperationSer.spareInterTurnToPage;
        $scope.spareHostComputerMessages=disasterOperationSer.spareHostComputerMessages;
        $scope.spareInterStateMessages=disasterOperationSer.spareInterStateMessages;
        $scope.spareApplianceMessages=disasterOperationSer.spareApplianceMessages;
        $scope.colseModal=disasterOperationSer.colseModal;
        $scope.myForm=disasterOperationSer.myForm;
        $scope.southData=disasterOperationSer.southData;
        $scope.dgData=disasterOperationSer.dgData;
        $scope.flowMessages=disasterOperationSer.flowMessages;
        $scope.getNfAppInfo=disasterOperationSer.getNfAppInfo;
        $scope.getNfHostInfo=disasterOperationSer.getNfHostInfo;
        $scope.getNfInterState=disasterOperationSer.getNfInterState;
        $scope.getDgAppInfo=disasterOperationSer.getDgAppInfo;
        $scope.getNowFlow=disasterOperationSer.getNowFlow;
        $scope.flowM=disasterOperationSer.flowM;
        $scope.clickPro=disasterOperationSer.clickPro;
        $scope.areaData=disasterOperationSer.areaData;
        $scope.changeHistoryTurnToPage=disasterOperationSer.changeHistoryTurnToPage;
        $scope.applianceTurnToPage=disasterOperationSer.applianceTurnToPage;
        $scope.interTurnToPage=disasterOperationSer.interTurnToPage;
        $scope.clickRadio=disasterOperationSer.clickRadio;
        console.log($scope.flowM);
	}
	disasterOperationCtr.$inject = ['$scope','disasterOperationSer'];
})(angular);


