/**
 * Created by Administrator on 2017/2/7 0007.
 */
;(function (angular) {
  'use strict';
  angular.module('controllers.operationInfo',[]).controller('operationInfoCtrl', operationInfoCtrl);
  function operationInfoCtrl($scope,operationInfo) {
  	$scope.falgHostComputer = operationInfo.falgHostComputer;
    $scope.majorCoreState = operationInfo.majorCoreState;
  	$scope.majorCoreAppQuery = operationInfo.majorCoreAppQuery;
  	$scope.falgSpareCoreHostComputer = operationInfo.falgSpareCoreHostComputer;
  	$scope.clickHostComputer = operationInfo.clickHostComputer;
  	$scope.clickApp = operationInfo.clickApp;
  	$scope.clickInterState = operationInfo.clickInterState;
  	$scope.clickGaojing = operationInfo.clickGaojing;
  	$scope.clickMajorCore = operationInfo.clickMajorCore;
  	$scope.clickSpareCore = operationInfo.clickSpareCore;
  	$scope.clickDisasterState = operationInfo.clickDisasterState;
  	$scope.clickDataBaseCopyState = operationInfo.clickDataBaseCopyState;
  	$scope.clickFileDataCopyState = operationInfo.clickFileDataCopyState;
  	$scope.clickDisasterInterState = operationInfo.clickDisasterInterState;
  	$scope.clickDisasterGaojing = operationInfo.clickDisasterGaojing;
  	$scope.clickSpareCoreHostComputer = operationInfo.clickSpareCoreHostComputer;
  	$scope.clickSpareCoreApp = operationInfo.clickSpareCoreApp;
  	$scope.clickSpareCoreInterState = operationInfo.clickSpareCoreInterState;
  	$scope.clickSpareCoreGaojing = operationInfo.clickSpareCoreGaojing;
  	$scope.falgSpareCoreGaojing = operationInfo.falgSpareCoreGaojing;
  	$scope.falgSpareCoreApp = operationInfo.falgSpareCoreApp;
  	$scope.falgSpareCoreInter = operationInfo.falgSpareCoreInter;
  	$scope.disasterState = operationInfo.disasterState;
  	$scope.spareCoreState = operationInfo.spareCoreState;
  	$scope.falgGaojing = operationInfo.falgGaojing;
  	$scope.falgInter = operationInfo.falgInter;
  	$scope.falgApp = operationInfo.falgApp;
  	$scope.load = operationInfo.load;
  	$scope.catalog = operationInfo.catalog;
  	$scope.majorCoreHostQuery = operationInfo.majorCoreHostQuery;
  	$scope.hostComputerMessage_new = operationInfo.hostComputerMessage_new;
  	$scope.applianceMessage_new = operationInfo.applianceMessage_new;
  	$scope.interStateMessage_new = operationInfo.interStateMessage_new;
  	$scope.giveAnlarmState = operationInfo.giveAnlarmState;
  	$scope.spareHostComputerMessage_new = operationInfo.spareHostComputerMessage_new;
  	$scope.spareApplianceMessage_new = operationInfo.spareApplianceMessage_new;
  	$scope.spareInterStateMessage_new = operationInfo.spareInterStateMessage_new;
  	$scope.spareGiveAnlarmState = operationInfo.spareGiveAnlarmState;
  	$scope.dataBaseCopyStateMessage = operationInfo.dataBaseCopyStateMessage;
  	$scope.disasterInterStateMessage = operationInfo.disasterInterStateMessage;
    $scope.disasterGiveAnlarmState = operationInfo.disasterGiveAnlarmState;
    $scope.majorCoreHostStyle = operationInfo.majorCoreHostStyle;
    $scope.majorCoreAppStyle = operationInfo.majorCoreAppStyle;
    $scope.majorCoreInterStyle = operationInfo.majorCoreInterStyle;
    $scope.majorCoreGaoJingStyle = operationInfo.majorCoreGaoJingStyle;
    $scope.initDate = operationInfo.initDate;
    $scope.judgeNumber = operationInfo.judgeNumber;
    $scope.datas = operationInfo.datas;
    $scope.getEndTime = operationInfo.getEndTime;
    $scope.stopSwitch = operationInfo.stopSwitch;
    $scope.nowDate = operationInfo.nowDate;
    $scope.clickPass = operationInfo.clickPass;
    $scope.falg = operationInfo.falg;
    $scope.falg_stop = operationInfo.falg_stop;
    $scope.switchNumber = operationInfo.switchNumber;
    $scope.sendSerialNumber = operationInfo.sendSerialNumber;
    $scope.initQueryParam = operationInfo.initQueryParam();
    $scope.setCurrentPageHost = operationInfo.setCurrentPageHost;
    $scope.setCurrentPageApp = operationInfo.setCurrentPageApp;
    $scope.setCurrentPageNet = operationInfo.setCurrentPageNet;
  	$scope.setCurrentPageGaojing = operationInfo.setCurrentPageGaojing;
    $scope.setCurrentPageHost_dg = operationInfo.setCurrentPageHost_dg;
    $scope.setCurrentPageApp_dg = operationInfo.setCurrentPageApp_dg;
    $scope.setCurrentPageNet_dg = operationInfo.setCurrentPageNet_dg;
    $scope.setCurrentPageGaojing_dg = operationInfo.setCurrentPageGaojing_dg;
    $scope.setCurrentPageDataBaseCopyState = operationInfo.setCurrentPageDataBaseCopyState;
    $scope.setCurrentPageDisasterInterState = operationInfo.setCurrentPageDisasterInterState;
    $scope.setCurrentPageDisasterGaojing = operationInfo.setCurrentPageDisasterGaojing;
    $scope.setCurrentPageFileDataCopyState = operationInfo.setCurrentPageFileDataCopyState;
    $scope.fileDataCopyStateMessage = operationInfo.fileDataCopyStateMessage;
    $scope.instance = operationInfo.instance;
    $scope.setInstance = operationInfo.setInstance;
    $scope.clickAppRunState = operationInfo.clickAppRunState;
  };

  operationInfoCtrl.$inject = ['$scope','operationInfo'];
})(angular);